# Generated by Django 5.2.5 on 2025-09-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0004_course_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('courses', models.ManyToManyField(to='student.course')),
                ('students', models.ManyToManyField(to='student.student')),
            ],
        ),
    ]
