# Generated by Django 5.2.5 on 2025-09-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_course_student_course'),
        ('subject', '0003_alter_subject_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(related_name='subjects', to='student.student'),
        ),
    ]
